name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    if: github.repository == 'GDay/django-q2'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools poetry
          python -m pip install poetry
      - name: Build and publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: poetry --build --username=__token__ --password=${{ secrets.PYPI_TOKEN }} publish
